### ISSUE TITLE
Is it possible to add gradient to stroke?

### ISSUE THREAD

**Issue by RoachLin** [arunpkqt/CircularSlider#11]
<img width="316" alt="Snipaste_2023-09-05_17-34-23" src="https://github.com/arunpkqt/CircularSlider/assets/33180391/9051e220-26c1-4126-bb14-5a581a7a3cb4">

Hello, I want to make this, and I add these code to "ShapePath { id: progressShapePath }" in "CircularSlider.qml":
```
fillGradient: LinearGradient {
	x1: 0
	y1: 0
	x2: parent.width
	y2: parent.height

	GradientStop {
		position: 0
		color: "#3DE1B7"
	}
	GradientStop {
		position: 1
		color: "#00B7D0"
	}
}
```
but it fails.

[https://doc.qt.io/qt-6/qml-qtquick-shapes-shapepath.html](url)
I checked the doc and didn't find something like stroke gradient, so I want to ask you if it is possible to make a stroke gradient. Thanks!

**Comment by RoachLin** [comment]
I follow this page and solve it.
[https://webcache.googleusercontent.com/search?q=cache:yBwudR2TnUcJ:https://gist.github.com/SMR76/715def4b51cc96ef027abd184125db15](url)

**Comment by RoachLin** [comment]
> > I follow this page and solve it. [https://webcache.googleusercontent.com/search?q=cache:yBwudR2TnUcJ:https://gist.github.com/SMR76/715def4b51cc96ef027abd184125db15](url)
> 
> Hi, the link is no longer valid now, would you please kindly share it again, or share the code ? thanks

I keep a copy of it, but it is in the computer at company. I'm off work now, I will send it to you about 12 hours later.

**Comment by cvbird** [comment]
> > > I follow this page and solve it. [https://webcache.googleusercontent.com/search?q=cache:yBwudR2TnUcJ:https://gist.github.com/SMR76/715def4b51cc96ef027abd184125db15](url)
> > 
> > 
> > Hi, the link is no longer valid now, would you please kindly share it again, or share the code ? thanks
> 
> I keep a copy of it, but it is in the computer at company. I'm off work now, I will send it to you about 12 hours later.

Thanks for your kindly help.

**Comment by RoachLin** [comment]
> > > > I follow this page and solve it. [https://webcache.googleusercontent.com/search?q=cache:yBwudR2TnUcJ:https://gist.github.com/SMR76/715def4b51cc96ef027abd184125db15](url)
> > > 
> > > 
> > > Hi, the link is no longer valid now, would you please kindly share it again, or share the code ? thanks
> > 
> > 
> > I keep a copy of it, but it is in the computer at company. I'm off work now, I will send it to you about 12 hours later.
> 
> Thanks for your kindly help.

[Circular Slider Gradient.zip](https://github.com/arunpkqt/CircularSlider/files/12853570/Circular.Slider.Gradient.zip)

**Comment by cvbird** [comment]
> > > > > I follow this page and solve it. [https://webcache.googleusercontent.com/search?q=cache:yBwudR2TnUcJ:https://gist.github.com/SMR76/715def4b51cc96ef027abd184125db15](url)
> > > > 
> > > > 
> > > > Hi, the link is no longer valid now, would you please kindly share it again, or share the code ? thanks
> > > 
> > > 
> > > I keep a copy of it, but it is in the computer at company. I'm off work now, I will send it to you about 12 hours later.
> > 
> > 
> > Thanks for your kindly help.
> 
> [Circular Slider Gradient.zip](https://github.com/arunpkqt/CircularSlider/files/12853570/Circular.Slider.Gradient.zip)

Got it with many thanks. :)
