### ISSUE TITLE
 "QtQuick.Shapes" is not installed

### ISSUE THREAD

**Issue by rajeabhilash** [arunpkqt/CircularSlider#9]
file:/UserDailyRoutine.qml:78: Type CircularSlider unavailable
file:/CircularSlider.qml:4: module "QtQuick.Shapes" is not installed

**Comment by arunpkqt** [comment]
@rajeabhilash which version of Qt you are using to build your application?

**Comment by arunpkqt** [comment]
@rajeabhilash Do you still have an issue with the import modules?

**Comment by rajeabhilash** [comment]
The issue is with the qt installation, It is resolved now, Thank you Arun for looking into it.!
Happy Coding.
